### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by priyansh32** [NITK-KODE/cms-api#11]
**How are we authenticating users?**
Instead of sessions, we can use JWT; minimal configuration is required as compared to sessions.
What do you guys think?

I would like to work on Google OAuth and JWT!

**Comment by priyansh32** [comment]
+ We should separate DB logic into a separate file `src/services/db.js`

**Comment by Utkar5hM** [comment]
I have almost setup session(stored on mongodb) with the help of passport.js. we can use multiple strategies with it for logging in for easy authentication via google Oauth or any other strategy from various providers.
Will test some things out and make  pr by night for the basic structure update, if Jwt has any noticiable advantages, we can switch to it.

**Comment by priyansh32** [comment]
I think jwt integrates better with APIs, It need not save anything on the server-side like sessions. Logout can be handled completely on the client side. yeah, we can go with sessions too, that is equally good.
