### ISSUE TITLE
Redirects and flash messages

### ISSUE THREAD

**Issue by priyansh32** [NITK-KODE/cms-api#23]
``https://github.com/NITK-KODE/cms-api/blob/41fe6f3405a90c07506f8f55a50b8c2e0e2e98ae/src/routes/users.js#L30-L38

The failureRedirect redirects to `GET login`, which does not exist. And if it does to `POST login,` that would be an infinite loop.  
Since we are building REST API, we need not redirect to a different route on failure; we can return to the client that the login was unsuccessful. The front-end can handle things based on responses received from the API.

Let us return responses in a consistent manner.
```js
res.status(400).json({
                success: false,
                message: "You have already voted once."
            }) 
```
Check out [this repo](https://github.com/BenzeneAlcohol/voting-app/blob/main/server/controllers/pollController.js) by @BenzeneAlcohol

**Comment by famousfive1** [comment]
Hey, I did an implementation for this. Can you check it out and see if it's what you wanted?
(https://github.com/famousfive1/competition-management-system/commit/69cd3897af621b402785dfdca5bcf74d1c241e6a)

**Comment by Utkar5hM** [comment]
You can check the comments.

**Comment by Utkar5hM** [comment]
I will fix other requests with success inside  according to this. I have currently moved passport's authentication function to controller's folder according to the code of @famousfive1 . adding `success:false` in all error returns instead of just message with status code or redirects..


> Let us return responses in a consistent manner.
> 
> ```js
> res.status(400).json({
>                 success: false,
>                 message: "You have already voted once."
>             }) 
> ```
