### ISSUE TITLE
some routes can be improved

### ISSUE THREAD

**Issue by priyansh32** [NITK-KODE/cms-api#34]
Currently there are two functions in `src/controllers/organizations` named `index` and `instituteIndex`

`index` fetched all organizations (I am not sure about the route of this function)  

`InstituteIndex` 
- fetches organizations belonging to a particular institute. 
- Route: `{{baseURL}}/institutes/:instituteId/organizations`

We can use a single route to get required organizations using query params.

**Comment by Ashley936** [comment]
I couldn't find the route for index function anywhere. I don't think it's even needed.
