### ISSUE TITLE
Dockerise the application

### ISSUE THREAD

**Issue by priyansh32** [NITK-KODE/cms-api#36]
## Resources
- https://nodejs.org/en/docs/guides/nodejs-docker-webapp/

**Comment by zatch3301** [comment]
Assign it to me I'll do it.

**Comment by priyansh32** [comment]
sure @zatch3301, Go ahead

**Comment by priyansh32** [comment]
@zatch3301 Let me know if you aren't working in it, I can assign it to someone else. If you are facing any problems, Do share.

**Comment by zatch3301** [comment]
I tried making dockerfile but should it only consist of dev ..?

**Comment by priyansh32** [comment]
Can you please elaborate, what do you mean by dev?

**Comment by zatch3301** [comment]
Your main application start with npm run dev right.?

**Comment by priyansh32** [comment]
No! use `npm start`, 
Environment variables can be set separately while starting the container.

**Comment by zatch3301** [comment]
I can't run the app without the secrets or keys.

**Comment by zatch3301** [comment]
I'll add the Dockerfile from my end but i dont have the keys so you can check on your end.

**Comment by priyansh32** [comment]
Yeah sure,
Or
```
PORT=8080
NODE_ENV=development
DB_URL=mongodb://localhost:27017/cms-nitk

JWT_SECRET = OHHO_VERY_WEIRD
```
Application will run with only this four variables, you can use any random key for JWT secret. If you don't have a local MongoDB set up. No worries! Create a PR, I will test it.

**Comment by zatch3301** [comment]
Done 
#43 
check once.
