### ISSUE TITLE
Add heroku.yml to deploy container to heroku

### ISSUE THREAD

**Issue by priyansh32** [NITK-KODE/cms-api#45]
Resources: [https://devcenter.heroku.com/articles/build-docker-images-heroku-yml](https://devcenter.heroku.com/articles/build-docker-images-heroku-yml)

**Comment by dhananjay8968** [comment]
assign me to this issue

**Comment by priyansh32** [comment]
Sure @dhananjay8968, I have assigned you the issue
Looking forward to your contribution 😄
