### ISSUE TITLE
Sanitizing mongo queries

### ISSUE THREAD

**Issue by Utkar5hM** [NITK-KODE/cms-api#58]
refer to the [Express Mongoose Sanitize](https://www.npmjs.com/package/express-mongo-sanitize) npm package, preffered for sanitzation to protect against no-sql injection.

**Comment by NeerajGartia21** [comment]
I would like to work on this issue.

**Comment by Utkar5hM** [comment]
Sure @NeerajGartia21 ! I have assigned you the issue.
Looking forward to your contribution .
